spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stripe
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
stripe:
  endpoint:
    secret: whsec_2b66c40ce2661d775624ef1ffb4b0337ec49092a94d076de63723642494f9d1e
  secret:
    key: sk_test_51Q4PTACTPGbmXchM72Wf66krXyufTQxRDk3Fq3fNJ2LJeKrOyHV6YtlEqTgbERHL4AWqUYwt5I4wvg76zHCTOCvY00TXH0wfNK